### ISSUE TITLE
How to deploy this?

### ISSUE THREAD

**Issue by guysoft** [thefourthone/extrusiongen#1]
How to deploy this?
If I try placing it in www it get some error about GL not working, even though I have opengl working

**Comment by TheThirdOne** [comment]
I am not sure what problem you are having, but there is a site up at http://dildogenerator.de/. This repository was an attempt to make this safe for a school setting. I didn't really complete it in 2014 and its been untouched since then.

**Comment by guysoft** [comment]
Oh, ok, 
1. The sources say "dildo-generator.com". So I guess you should update your readme :)
2. I did:
```
cd /var/www
git clone https://github.com/thefourthone/extrusiongen
```
point browser to ``localhost/extrusiongen/main.html``
and got this:
![screenshot_20180913_133648](https://user-images.githubusercontent.com/325670/45483652-3e99b300-b75a-11e8-9d8d-8ddcbe91b108.png)

The website at  http://dildogenerator.de/ works without the opengl error.

Upon inspecting I can see that this repo has version 1.0.0. and the versions reported by the site is 1.0.1:

https://github.com/thefourthone/extrusiongen/blob/master/main.js#L12

vs:
```javascript
curl  http://dildogenerator.de/js/main.js | head -n 20
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
/**
 * This is just a (dirty) collection of javascript functions the main page
 * uses.
 *
 *
 * The actual generator logic is located in the class files.
 *
 *
 * @author   Ikaros Kappler
 * @date     2013-10-13
 * @modified 2015-01-30 Ikaros Kappler (GET params handling: added decodeURI()).
 * @version  1.0.1
 **/

```
requesting you reopen this issue, since its valid.

**Comment by TheThirdOne** [comment]
For solving the NoWebGL error, it should be solvable by looking through the code for this and the site that is currently up. The reason I closed it is because I am not going to put effort into solving this, and the solution is straightforward if tedious.
